import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import ProviderWrapper from "@/components/ProviderWrapper/ProviderWrapper";
import { Poppins } from "next/font/google";
import Script from "next/script";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Tunem",
    description: "Generated by bd calling it.",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={poppins.className} >
            <head>
                {/* ✅ TrustBox script */}
                <Script
                    src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js"
                    strategy="afterInteractive"
                />
                {/* ✅ End TrustBox script */}
            </head>
            <body
                suppressHydrationWarning
                className={` antialiased`}
            >

                <main className={` w-full `} >
                    <ProviderWrapper>
                        {
                            children
                        }
                    </ProviderWrapper>
                </main>
            </body>
        </html>
    );
}
